development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

  airbrake_api_key: ""
  secret_token: EAOCgGpr6msOJgeIzF9L6aScXN8KYXL4
  session_key: Z233WWMecJV7CgDjEkwdONwOC6hglTgF
  mobile_id:
    endpoint_url: https://openxades.org:8443/DigiDocService
    authentication:
      message_to_display: Autentimine
      service_name: Testimine
    sign:
      message_to_display: Maksete allkirjastamine
      service_name: Testimine

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000
